export enum UserAccessFunctionName {
  ALL = "ALL",
  SUBSCRIPTIONS = "SUBSCRIPTIONS",
  SUPPORT = "SUPPORT",
  SETTINGS = "SETTINGS",
  USER_REPORT = "USER_REPORT",
  BARBER_MANAGEMENT = "BARBER_MANAGEMENT",
  ADMIN_MANAGEMENT = "ADMIN_MANAGEMENT",
  CUSTOMER = "CUSTOMER",
  SALOON_OWNER = "SALON_OWNER",
  PREMIUM_SUBSCRIBERS = "PREMIUM_SUBSCRIBERS",
  ADS_PROMOTIONS = "ADS_PROMOTIONS"
}